name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy-docs:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn install

      - name: Deploy a docs site
        run: |-
          cd docs
          yarn vercel deploy --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
